apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigquery-controller
  labels:
    name: bigquery-controller
spec:
  replicas: ${num_replica}
  selector:
    matchLabels:
      name: bigquery-controller
  template:
    metadata:
      labels:
        name: bigquery-controller
    spec:
      containers:
      - name: bigquery
        image: gcr.io/${project_id}/pubsub_bq:${tag_id}
        env:
        - name: PROCESSINGSCRIPT
          value: pubsub-to-bigquery
        # Change this to your pubsub topic
        - name: PUBSUB_TOPIC
          value: projects/${project_id}/topics/${topic_name}
        # Change this to your project ID.
        - name: PROJECT_ID
          value: ${project_id}
        # Change the following two settings to your dataset and table.
        - name: BQ_DATASET
          value: ${bq_dataset}
        - name: BQ_TABLE
          value: ${bq_table}
