apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      name: twitter-stream
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub
        image: gcr.io/${project_id}/pubsub_bq:${tag_id}
        env:
        - name: PROCESSINGSCRIPT
          value: twitter-to-pubsub
        # Change this to your pubsub topic
        - name: PUBSUB_TOPIC
          value: projects/${project_id}/topics/${topic_name}
        # Change the following four settings to your twitter credentials
        # information.
        - name: CONSUMERKEY
          value: ${tw_key}
        - name: CONSUMERSECRET
          value: ${tw_secret}
        - name: ACCESSTOKEN
          value: ${tw_token}
        - name: ACCESSTOKENSEC
          value: ${tw_token_sec}
        - name: TWKEYWORDS
          value: ${tw_keywords}

